# Generated by Django 4.2.3 on 2023-07-11 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('birthday', 'Aniversário'), ('category_a', 'Categoria A'), ('category_b', 'Categoria B'), ('category_c', 'Categoria C')], max_length=15)),
                ('private', models.BooleanField(help_text='definir como True torna preciso a aceitação da requisição de participação')),
                ('free', models.BooleanField(help_text='definir como true significa que é um evento livre, sem restrição de idade')),
                ('start_date_time', models.DateTimeField()),
                ('final_date_time', models.DateTimeField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='event_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
