# Generated by Django 4.2.3 on 2023-07-12 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='free',
            field=models.BooleanField(help_text='definir como True significa que é um evento livre, sem restrição de idade'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
