# Generated by Django 4.2.3 on 2023-07-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_event_event_banner_alter_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(default='event_banners/default_event_banner.png', upload_to='event_banners'),
        ),
    ]
