# Generated by Django 4.2.3 on 2023-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_event_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.JSONField(),
        ),
    ]
