# Generated by Django 4.2.3 on 2023-07-18 02:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0008_event_requests_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Solicitation',
        ),
    ]
