# Generated by Django 4.2.3 on 2023-07-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_rename_request_solicitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='requests',
        ),
    ]
