# Generated by Django 4.2.3 on 2023-08-05 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_remove_event_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_banner',
            field=models.FileField(default='/default_event_banner.png', upload_to='event_banners'),
        ),
        migrations.AlterField(
            model_name='event',
            name='final_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
