# Generated by Django 4.2.3 on 2023-08-06 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0011_alter_event_event_banner_alter_event_final_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='banned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
