# Generated by Django 4.2.3 on 2023-07-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0002_alter_user_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(default=17),
            preserve_default=False,
        ),
    ]
