# Generated by Django 4.2.3 on 2023-07-19 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0004_alter_user_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.FileField(blank=True, default='user_img.png', null=True, upload_to='user_img'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar em um formato válido.', regex='^\\+\\d{2} \\d{5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(default=None),
        ),
    ]
