# Generated by Django 4.2.3 on 2023-07-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0005_user_user_img_alter_phonenumber_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.FileField(default='/user_img/user_img.png', upload_to='user_img'),
        ),
    ]
