# Generated by Django 4.2.3 on 2023-07-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0006_alter_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
