# Generated by Django 4.2.3 on 2023-07-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
